apiVersion: v1
kind: Service
metadata:
  name: sqlserver-2019-service
  namespace: database
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
