apiVersion: v1
kind: Pod
metadata:
  name: nettools-2
  namespace: confluent
spec:
  containers:
  - name: nettools
    image: jrecord/nettools:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: k3d-cluster-agent-2
  restartPolicy: Never