apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  keyConverterType: io.confluent.connect.avro.AvroConverter
  valueConverterType: io.confluent.connect.avro.AvroConverter
  replicas: 3
  image:
    application: confluentinc/cp-server-connect:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  # build:
  #   type: onDemand
  #   onDemand:
  #     plugins:
  #       locationType: url
  #       url:
  #         - name: kafka-connect-jdbc # the url is used here as we needed to build our own connector lib to include the mysql jdbc jar
  #           archivePath: https://raw.githubusercontent.com/confluentinc/confluent-kubernetes-examples/master/hybrid/ccloud-JDBC-mysql/confluentinc-kafka-connect-jdbc-10.2.5.zip
  #           checksum: 9d033fabac89ec0b35a97246f7ca3a36800bcb402ccfbd76adebd4c4c9ca6e7d6a044a9162383a18f99400893581b55a87b9fe89e35276507e9a3fb6cff3fda0
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub
        confluentHub:
          - name: kafka-connect-jdbc
            owner: confluentinc
            version: 10.2.5
          - name: kafka-connect-hdfs3
            owner: confluentinc
            version: latest
          - name: kafka-connect-hdfs
            owner: confluentinc
            version: latest
          - name: debezium-connector-postgresql
            owner: debezium
            version: 2.2.1
          - name: kafka-connect-transform-common
            owner: jcustenborder
            version: 0.1.0.58
          # - name: debezium-connector-sqlserver
          #   owner: debezium
          #   version: latest
        locationType: url
        url:
          - name: debezium-connector-sqlserver
            archivePath: https://raw.githubusercontent.com/Thaiph1308/lab-provisioning/main/debezium-debezium-connector-sqlserver-2.5.1.zip
            #checksum: aafb2d177a2ecd9a9b613ee54f95e99b38c88442668683115e5a573abc2473cdf5d86111596a703a04a24a8faa864306bbfd0218d78483bfddc7897ac9abbd69
            checksum: a672940a95520e68b0739b0a51723b11798f615783360b01232a6f124c8e7b60260478ce5e7866d49032b0742930b061cbfa3faed5bae77d43ef0cab26821930
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
    schemaRegistry:
      url: http://schemaregistry:8081
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true